run:
  # also lint files within /scripts. Those have "//go:build scripts" set.
  build-tags:
    - scripts
issues:
  fix: true
linters:
  disable-all: true
  enable:
    # https://github.com/golangci/golangci-lint#enabled-by-default-linters
    # Additional linters you want to activate may be specified here...

    # ---
    # https://github.com/maratori/testpackage
    # used to enforce blackbox testing
    - testpackage

    # ---
    # https://github.com/securego/gosec
    # inspects source code for security problems by scanning the Go AST.
    - dupl
    - govet
    # Formatting Check
    - gofmt
    - goimports
    # Complexity Check
    - gocyclo
    - nakedret
    # Style Check
    # ---
    # https://github.com/mgechev/revive
    # replacement for the now deprecated official golint linter, see https://github.com/golang/go/issues/38968
    #- revive
    - gochecknoglobals
    - gosimple
    - goconst
    - misspell
    - unconvert
    # Unused Code Check
    - varcheck
    - deadcode
    - unparam
    - ineffassign
    - unused
    # Bug Finding
    - errcheck
    - gosec
    - scopelint
    - errcheck
    - staticcheck
    # Performance Check
    - maligned
    - gocritic
    - prealloc
